version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TestWebForPipeline/TestWebForPipeline.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output TestWebForPipeline/TestWebForPipeline.csproj
artifacts:
  files:
    - TestWebForPipeline/build_output/**/*