version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - $(aws ecs describe-clusters –cluster code-pipeline-cluster)
      - $(aws ecs run-task –task-definition testwebforpipeline-task:2 –cluster code-pipeline-cluster)
      - docker build -f "TestWebForPipeline/Dockerfile" -t testwebforpipeline .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker tag testwebforpipeline:latest 690264925639.dkr.ecr.us-east-1.amazonaws.com/testwebforpipeline:latest
      - docker push 690264925639.dkr.ecr.us-east-1.amazonaws.com/testwebforpipeline:latest
