version: 0.2

phases:
  pre_build:
    commands:
      - echo Set Vars
      - REPOSITORY_URI=690264925639.dkr.ecr.us-east-1.amazonaws.com/testwebforpipeline
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t testwebforpipeline .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - docker tag testwebforpipeline:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      